application: 1001diena 
version: 2-0-5-3
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
- url: /
  script: main.py

- url: /admin.*
  login: required
  script: admin.py

- url: /l/(\d{1,2})
  script: main.py

- url: /s/(\d{1,2}|10[10])/(\d{1,2})
  script: stuff.py

- url: /s/(\d{1,2}|10[10])
  script: stuff.py

- url: /stuff
  script: stuff.py

- url: /info
  script: info.py

# Static directories
- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /img
  static_dir: static/img
